CREATE TABLE UTILISATEUR
(
    NUM_UTI INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOM_UTI VARCHAR(20) NOT NULL,
    PRENOM_UTI VARCHAR(20) NOT NULL,
    MDP_UTI varchar(50) NOT NULL,
    ADMINISTRATEUR BOOLEAN NOT NULL DEFAULT 0,
    DATE_PAIEMENT DATE,
    CODE_POSTAL INT NOT NULL,
    VILLE VARCHAR(15) NOT NULL,
    MAIL_UTI VARCHAR(20) NOT NULL
);


INSERT INTO UTILISATEUR(NOM_UTI, PRENOM_UTI, MDP_UTI, ADMINISTRATEUR, CODE_POSTAL, VILLE, MAIL_UTI)
VALUES('admin', 'admin', 'd033e22ae348aeb5660fc2140aec35850c4da997', 1, '13800', 'ISTRES', 'qbelaghrouz@gmail.com');


CREATE TABLE AUTEUR
(
    ID_AUTEUR INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOM_AUTEUR VARCHAR(10) NOT NULL,
    PRENOM_AUTEUR VARCHAR(10) NOT NULL
);


INSERT INTO AUTEUR(NOM_AUTEUR, PRENOM_AUTEUR) VALUES('krakauer', 'jon');
INSERT INTO AUTEUR(NOM_AUTEUR, PRENOM_AUTEUR) VALUES('Delannoy', 'Claude');


CREATE TABLE OEUVRE
(
    COTE_OEUVRE VARCHAR(8) NOT NULL PRIMARY KEY,
    TITRE_OEUVRE VARCHAR(20) NOT NULL,
    ANNEE_PARUTION YEAR NOT NULL,
    ID_AUTEUR INT NOT NULL,
    ID_CATEGORIE INT NOT NULL,
    ID_SOUS_CATEGORIE INT NOT NULL
    illustration varchar(30) NOT NULL
);

INSERT INTO OEUVRE VALUES('LD001', 'INTO THE WILD', '1996', 1, 1, 1, 'intothewild.jpg');
INSERT INTO OEUVRE VALUES('L0002', 'Programmer en langage c++', '1992', 2, 2, 2);


CREATE TABLE MOT_CLE
(
    ID_MOT_CLE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LIBELLE_MOT_CLE VARCHAR(20) NOT NULL
);


INSERT INTO MOT_CLE(LIBELLE_MOT_CLE) VALUES('aventure');
INSERT INTO MOT_CLE(LIBELLE_MOT_CLE) VALUES('informatique');

CREATE TABLE MOT_CLE_OEUVRE
(
    ID_MOT_CLE INT NOT NULL,
    COTE_OEUVRE VARCHAR(8) NOT NULL
);

INSERT INTO MOT_CLE_OEUVRE VALUES(1, 'L0001');
INSERT INTO MOT_CLE_OEUVRE VALUES(2, 'L0002');

CREATE TABLE CATEGORIE
(
    ID_CATEGORIE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LIBELLE_CATEGORIE VARCHAR(30) NOT NULL
);

INSERT INTO CATEGORIE(LIBELLE_CATEGORIE) VALUES('divertissement');
INSERT INTO CATEGORIE(LIBELLE_CATEGORIE) VALUES('sciences');

CREATE TABLE SOUS_CATEGORIE
(
    ID_SOUS_CATEGORIE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LIBELLE_SOUS_CATEGORIE VARCHAR(30) NOT NULL,
    ID_CATEGORIE INT NOT NULL,
    CONSTRAINT fk_sous_cat FOREIGN KEY(ID_CATEGORIE) REFERENCES CATEGORIE(ID_CATEGORIE)
);

INSERT INTO SOUS_CATEGORIE(LIBELLE_SOUS_CATEGORIE, ID_CATEGORIE) VALUES('aventure', 1);
INSERT INTO SOUS_CATEGORIE(LIBELLE_SOUS_CATEGORIE, ID_CATEGORIE) VALUES('informatique', 2);

CREATE TABLE COMMENTAIRE
(
  ID_COM int not null AUTO_INCREMENT PRIMARY KEY,
  TEXTE_COM mediumtext not null,
  DATE_COM datetime not null,
  NUM_UTI int UNSIGNED not null,
  ID_OEUVRE int not null,
  CONSTRAINT fk_com_num_uti FOREIGN KEY(NUM_UTI) REFERENCES UTILISATEUR(NUM_UTI),
  CONSTRAINT fk_com_id_oeuvre FOREIGN KEY(ID_OEUVRE) REFERENCES OEUVRE(ID_OEUVRE)
);

INSERT INTO COMMENTAIRE(TEXTE_COM, DATE_COM, NUM_UTI, ID_OEUVRE) VALUES('Super livre, à lire pour apprendre l\'essentiel du langage' CURRENT_DATE, 1, 4);

CREATE TABLE LIVRE
(
  ID_LIVRE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ID_OEUVRE INT NOT NULL,
  DATE_ACHAT DATE NOT NULL,
  STATUT BOOLEAN NOT NULL DEFAULT 0,
  CONSTRAINT fk_livre_id_oeuvre FOREIGN KEY(ID_OEUVRE) REFERENCES OEUVRE(ID_OEUVRE)
);

CREATE TABLE RESERVATION
(
  ID_RESERVATION INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ID_LIVRE INT NOT NULL,
  NUM_UTI INT UNSIGNED NOT NULL,
  DATE_RESERVATION DATE NOT NULL,
  DATE_ACCEPTATION DATE,
  CONSTRAINT fk_resa_id_livre FOREIGN KEY(ID_LIVRE) REFERENCES LIVRE(ID_LIVRE),
  CONSTRAINT fk_resa_num_uti FOREIGN KEY(NUM_UTI) REFERENCES UTILISATEUR(NUM_UTI)
);

CREATE TABLE EMPRUNT
(
  ID_EMPRUNT INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ID_LIVRE INT NOT NULL,
  NUM_UTI INT UNSIGNED NOT NULL,
  DATE_PRET DATE,
  DATE_RETOUR DATE,
  RENOUVELLEMENT BOOLEAN NOT NULL DEFAULT 0,
  STATUT BOOLEAN NOT NULL DEFAULT 0,
  CONSTRAINT fk_emprunt_id_livre FOREIGN KEY(ID_LIVRE) REFERENCES LIVRE(ID_LIVRE),
  CONSTRAINT fk_emprunt_num_uti FOREIGN KEY(NUM_UTI) REFERENCES UTILISATEUR(NUM_UTI)
);
