--DONE
CREATE TABLE UTILISATEUR
(
    NUM_UTI INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOM_UTI VARCHAR(20) NOT NULL,
    PRENOM_UTI VARCHAR(20) NOT NULL,
    MDP_UTI varchar(50) NOT NULL,
    ADMINISTRATEUR BOOLEAN NOT NULL DEFAULT 0,
    DATE_PAIEMENT DATE,
    CODE_POSTAL INT NOT NULL,
);

--DONE
INSERT INTO UTILISATEUR(NOM_UTI, PRENOM_UTI, MDP_UTI, ADMINISTRATEUR, CODE_POSTAL, VILLE, MAIL_UTI)
VALUES('admin', 'admin', 'd033e22ae348aeb5660fc2140aec35850c4da997', 1, '13800', 'ISTRES', 'qbelaghrouz@gmail.com');

--DONE
CREATE TABLE AUTEUR
(
    ID_AUTEUR INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOM_AUTEUR VARCHAR(10) NOT NULL,
    PRENOM_AUTEUR VARCHAR(10) NOT NULL
);

--DONE
INSERT INTO(NOM_AUTEUR, PRENOM_AUTEUR)
VALUES('krakauer', 'jon');

--DONE
CREATE TABLE OEUVRE
(
    COTE_OEUVRE VARCHAR(8) NOT NULL PRIMARY KEY,
    TITRE_OEUVRE VARCHAR(20) NOT NULL,
    ANNEE_PARUTION YEAR NOT NULL,
    ID_AUTEUR INT NOT NULL,
    CONSTRAINT fk_auteur FOREIGN KEY(ID_AUTEUR) REFERENCES AUTEUR(ID_AUTEUR)
);

--DONE
CREATE TABLE MOT_CLE
(
    ID_MOT_CLE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LIBELLE_MOT_CLE VARCHAR(20) NOT NULL
);

--DONE
INSERT INTO MOT_CLE(LIBELLE_MOT_CLE) VALUES('aventure')

CREATE TABLE MOT_CLE_OEUVRE
(
    ID_MOT_CLE INT NOT NULL,
    COTE_OEUVRE VARCHAR(8) NOT NULL
);